-- 비즈플레이 추가
CREATE TABLE BP_0411A (
 RESULT_CD VARCHAR2(8),
 RESULT_MG VARCHAR2(255),
 NEXT_KEY VARCHAR2(200),
 BIZ_NO VARCHAR2(20),
 BANK_CD VARCHAR2(16),
 CARD_TYPE VARCHAR2(1),
 CARD_NO VARCHAR2(19),
 CARD_B_TYPE VARCHAR2(1),
 SEQ VARCHAR2(10),
 APV_DT VARCHAR2(8),
 APV_NO VARCHAR2(44),
 APV_TM VARCHAR2(6),
 APV_CAN_YN  VARCHAR2(2),
 APV_CAN_DT VARCHAR2(8),
 SETL_SCHE_DT VARCHAR2(8),
 APR_AMT NUMBER(20),
 APR_SPLY_AMT NUMBER(20),
 APR_VAT_AMT NUMBER(20),
 BUY_SUM NUMBER(20),
 SPLY_AMT NUMBER(20),
 VAT_AMT NUMBER(20),
 SRV_FEE NUMBER(20),
 COMM NUMBER(20),
 OVRS_USE_YN VARCHAR2(1),
 CURR_CD VARCHAR2(3),
 CURR_AMT NUMBER(20),
 ORG_SPLY_AMT NUMBER(20),
 ORG_VAT NUMBER(20),
 ITLM_MMS_CNT VARCHAR2(2),
 MEST_NM VARCHAR2(50),
 MEST_NO VARCHAR2(20),
 MEST_TAXT_TYP_INFO VARCHAR2(20),
 MEST_BIZ_NO VARCHAR2(10),
 MEST_REPR_NM VARCHAR2(50),
 MEST_TEL_NO VARCHAR2(14),
 MEST_ZIP_CD VARCHAR2(10),
 MEST_ADDR_1 VARCHAR2(200),
 MEST_ADDR_2 VARCHAR2(200),
 CARD_TPBZ_CD VARCHAR2(50),
 CARD_TPBZ_NM VARCHAR2(50),
 REG_GB VARCHAR2(1),
 BUY_YN VARCHAR2(1),
 PURCH_DATE VARCHAR2(8),
 ACQU_EXCH VARCHAR2(17),
 COLL_NO VARCHAR2(32),
 VAT_RFND_STS VARCHAR2(1),
 PROC_STS VARCHAR2(1),
 TRAN_KIND_CD VARCHAR2(20),
 TRAN_KIND_NM VARCHAR2(50),
 TRAN_KIND_ERP_CO_CD VARCHAR2(20),
 BIZ_UNIT_NM VARCHAR2(100),
 BIZ_UNIT_ERP_CD VARCHAR2(50),
 SUMMARY VARCHAR2(1000),
 USER_NM VARCHAR2(20),
 USER_ID VARCHAR2(20),
 USER_EMP_CD VARCHAR2(20),
 USER_EMP_OFFICE VARCHAR2(100),
 DEPT_NM VARCHAR2(20),
 DEPT_CD VARCHAR2(20),
 DEPT_ERP_CD VARCHAR2(20),
 R_USER_NM VARCHAR2(50),
 R_USER_ID VARCHAR2(50),
 R_EMP_ERP_CD VARCHAR2(20),
 R_USER_EMP_OFFICE VARCHAR2(100),
 R_DEPT_NM VARCHAR2(50),
 R_DEPT_ERP_CD VARCHAR2(20),
 LST_USER_ID VARCHAR2(20),
 LST_USER_EMP_CD VARCHAR2(20),
 LST_USER_DEPT_ERP_CD VARCHAR2(20),
 LST_MOD_DT VARCHAR2(16),
 ERP_CODE VARCHAR2(30),
 APPR_STS VARCHAR2(2),
 APPR_SUBJ VARCHAR2(200),
 APPR_CONT VARCHAR2(1000),
 ERP_ASST_CD VARCHAR2(20),
 ATT_IMG_YN VARCHAR2(1),
 ATT_IMG_CNT VARCHAR2(1),
 SUMMARY_2 VARCHAR2(1000),
 SUMMARY_3 VARCHAR2(1000),
 SUMMARY_4 VARCHAR2(1000),
 SUMMARY_5 VARCHAR2(1000),
 SUMMARY_6 VARCHAR2(1000),
 PPP_APPR_VOUCH_YN VARCHAR2(1),
 PPP_APPR_SEQ_NO VARCHAR2(20),
 RESERVE_01_NM VARCHAR2(100),
 RESERVE_01_CODE VARCHAR2(20),
 RESERVE_01_ERP_CD VARCHAR2(20),
 EVENT_DATETIME VARCHAR2(14),
 START_DTM VARCHAR2(14),
 END_DTM VARCHAR2(14),
 EVENT_DTM VARCHAR2(30),
 ASSET_DIV_NM VARCHAR2(50),
 ASSET_DEPT_NM VARCHAR2(50),
 ASSET_DIV_ERP_CD VARCHAR2(20),
 ASSET_DEPT_ERP_CD VARCHAR2(20),
 DEDCT_YN VARCHAR2(1),
 BIZ_UNIT_NM2 VARCHAR2(50),
 BIZ_UNIT_ERP_CD2 VARCHAR2(50),
 PAY_ACCOUNT_NO VARCHAR2(20),
 PAY_HOLDER_NAME VARCHAR2(20),
 PAY_BANK VARCHAR2(50),
 EXPN_PAY_DT VARCHAR2(8),
 EXPN_PRE_DT VARCHAR2(8),
 DOC_NO VARCHAR2(50),
 SUMMARY_7 VARCHAR2(1000),
 SUMMARY_8 VARCHAR2(1000),
 RSCH_CD VARCHAR2(20),
 RSCH_NM VARCHAR2(50),
 ADVC_CD VARCHAR2(20),
 ADVC_NM VARCHAR2(50),
 CARD_ERP_CD VARCHAR2(50),
 CARD_NICK_NM VARCHAR2(50),
 DRAFT_DATE VARCHAR2(8),
 PTL_ID VARCHAR2(10),
 USE_INTT_ID VARCHAR2(20),
 LST_APRV_DATE VARCHAR2(8),
 APPR_SEQ_NO VARCHAR2(20),
 RESOLLIST_SEQ_NO VARCHAR2(15),
 PROC_BANK_ACCT_NO VARCHAR2(20),
 PROC_HOLDER_NAME VARCHAR2(20),
 PROC_BANK_NM VARCHAR2(50),
 CAN_MG VARCHAR2(100),
 ERP_STAT_NO VARCHAR2(100),
 CAR_INFO VARCHAR2(20)
);

-- 비즈플레이 코멘트 추가
COMMENT ON COLUMN BP_0411A.RESULT_CD IS '결과코드';
COMMENT ON COLUMN BP_0411A.RESULT_MG IS '메세지';
COMMENT ON COLUMN BP_0411A.NEXT_KEY IS '다음결과키';
COMMENT ON COLUMN BP_0411A.BIZ_NO IS '사업자번호';
COMMENT ON COLUMN BP_0411A.BANK_CD IS '카드사코드';
COMMENT ON COLUMN BP_0411A.CARD_TYPE IS '카드(증빙)구분';
COMMENT ON COLUMN BP_0411A.CARD_NO IS '카드번호';
COMMENT ON COLUMN BP_0411A.CARD_B_TYPE IS '카드세부구분';
COMMENT ON COLUMN BP_0411A.SEQ IS '일련번호';
COMMENT ON COLUMN BP_0411A.APV_DT IS '승인일자';
COMMENT ON COLUMN BP_0411A.APV_NO IS '승인번호';
COMMENT ON COLUMN BP_0411A.APV_TM IS '승인시간';
COMMENT ON COLUMN BP_0411A.APV_CAN_YN  IS '승인취소여부';
COMMENT ON COLUMN BP_0411A.APV_CAN_DT IS '승인취소일자';
COMMENT ON COLUMN BP_0411A.SETL_SCHE_DT IS '결제예정일자';
COMMENT ON COLUMN BP_0411A.APR_AMT IS '신청금액';
COMMENT ON COLUMN BP_0411A.APR_SPLY_AMT IS '신청금액 기준 공급가액';
COMMENT ON COLUMN BP_0411A.APR_VAT_AMT IS '신청금액 기준 부가세액';
COMMENT ON COLUMN BP_0411A.BUY_SUM IS '승인금액';
COMMENT ON COLUMN BP_0411A.SPLY_AMT IS '공급금액';
COMMENT ON COLUMN BP_0411A.VAT_AMT IS '부가가치세액';
COMMENT ON COLUMN BP_0411A.SRV_FEE IS '봉사료';
COMMENT ON COLUMN BP_0411A.COMM IS '수수료';
COMMENT ON COLUMN BP_0411A.OVRS_USE_YN IS '해외사용여부';
COMMENT ON COLUMN BP_0411A.CURR_CD IS '통화코드';
COMMENT ON COLUMN BP_0411A.CURR_AMT IS '외화금액';
COMMENT ON COLUMN BP_0411A.ORG_SPLY_AMT IS '공급가액 원본';
COMMENT ON COLUMN BP_0411A.ORG_VAT IS '부가세 원본';
COMMENT ON COLUMN BP_0411A.ITLM_MMS_CNT IS '할부개월수';
COMMENT ON COLUMN BP_0411A.MEST_NM IS '가맹점명';
COMMENT ON COLUMN BP_0411A.MEST_NO IS '가맹점번호';
COMMENT ON COLUMN BP_0411A.MEST_TAXT_TYP_INFO IS '가맹점과세유형정보';
COMMENT ON COLUMN BP_0411A.MEST_BIZ_NO IS '가맹점사업자번호';
COMMENT ON COLUMN BP_0411A.MEST_REPR_NM IS '가맹점대표자명';
COMMENT ON COLUMN BP_0411A.MEST_TEL_NO IS '가맹점전화번호';
COMMENT ON COLUMN BP_0411A.MEST_ZIP_CD IS '가맹점우편번호';
COMMENT ON COLUMN BP_0411A.MEST_ADDR_1 IS '가맹점주소1';
COMMENT ON COLUMN BP_0411A.MEST_ADDR_2 IS '가맹점주소2';
COMMENT ON COLUMN BP_0411A.CARD_TPBZ_CD IS '카드업종코드';
COMMENT ON COLUMN BP_0411A.CARD_TPBZ_NM IS '카드업종명';
COMMENT ON COLUMN BP_0411A.REG_GB IS '등록구분';
COMMENT ON COLUMN BP_0411A.BUY_YN IS '매입여부';
COMMENT ON COLUMN BP_0411A.PURCH_DATE IS '매입일자';
COMMENT ON COLUMN BP_0411A.ACQU_EXCH IS '매입시적용환율';
COMMENT ON COLUMN BP_0411A.COLL_NO IS '매입추심번호';
COMMENT ON COLUMN BP_0411A.VAT_RFND_STS IS '부가세환급여부';
COMMENT ON COLUMN BP_0411A.PROC_STS IS '처리상태';
COMMENT ON COLUMN BP_0411A.TRAN_KIND_CD IS '거래종류코드';
COMMENT ON COLUMN BP_0411A.TRAN_KIND_NM IS '거래종류명';
COMMENT ON COLUMN BP_0411A.TRAN_KIND_ERP_CO_CD IS '거래종류 ERP 상대계정';
COMMENT ON COLUMN BP_0411A.BIZ_UNIT_NM IS '사업/프로젝트명';
COMMENT ON COLUMN BP_0411A.BIZ_UNIT_ERP_CD IS '구분 ERP 코드';
COMMENT ON COLUMN BP_0411A.SUMMARY IS '적요';
COMMENT ON COLUMN BP_0411A.USER_NM IS '카드 사용자 이름';
COMMENT ON COLUMN BP_0411A.USER_ID IS '최종 수정 사용자ID';
COMMENT ON COLUMN BP_0411A.USER_EMP_CD IS '카드 사용자 직원 코드';
COMMENT ON COLUMN BP_0411A.USER_EMP_OFFICE IS '카드 사용자 근무지';
COMMENT ON COLUMN BP_0411A.DEPT_NM IS '카드 사용자 부서명';
COMMENT ON COLUMN BP_0411A.DEPT_CD IS '부서코드';
COMMENT ON COLUMN BP_0411A.DEPT_ERP_CD IS '부서ERP코드';
COMMENT ON COLUMN BP_0411A.R_USER_NM IS '영수증 사용자 이름';
COMMENT ON COLUMN BP_0411A.R_USER_ID IS '영수증 사용자 ID';
COMMENT ON COLUMN BP_0411A.R_EMP_ERP_CD IS '영수증 사용자 ERP코드';
COMMENT ON COLUMN BP_0411A.R_USER_EMP_OFFICE IS '영수증 사용자 근무지';
COMMENT ON COLUMN BP_0411A.R_DEPT_NM IS '영수증 사용자 부서명';
COMMENT ON COLUMN BP_0411A.R_DEPT_ERP_CD IS '영수증 사용자 부서코드';
COMMENT ON COLUMN BP_0411A.LST_USER_ID IS '최종 수정 사용자ID';
COMMENT ON COLUMN BP_0411A.LST_USER_EMP_CD IS '최종 수정자 사원번호';
COMMENT ON COLUMN BP_0411A.LST_USER_DEPT_ERP_CD IS '최종 수정자 부서코드';
COMMENT ON COLUMN BP_0411A.LST_MOD_DT IS '최종수정일자';
COMMENT ON COLUMN BP_0411A.ERP_CODE IS 'ERP코드';
COMMENT ON COLUMN BP_0411A.APPR_STS IS '결재상태';
COMMENT ON COLUMN BP_0411A.APPR_SUBJ IS '품의 제목';
COMMENT ON COLUMN BP_0411A.APPR_CONT IS '품의 내용';
COMMENT ON COLUMN BP_0411A.ERP_ASST_CD IS '예산항목ERP코드';
COMMENT ON COLUMN BP_0411A.ATT_IMG_YN IS '증빙이미지 여부';
COMMENT ON COLUMN BP_0411A.ATT_IMG_CNT IS '증빙이미지 개수';
COMMENT ON COLUMN BP_0411A.SUMMARY_2 IS '내용2';
COMMENT ON COLUMN BP_0411A.SUMMARY_3 IS '내용 3';
COMMENT ON COLUMN BP_0411A.SUMMARY_4 IS '내용4';
COMMENT ON COLUMN BP_0411A.SUMMARY_5 IS '내용 5';
COMMENT ON COLUMN BP_0411A.SUMMARY_6 IS '내용 6';
COMMENT ON COLUMN BP_0411A.PPP_APPR_VOUCH_YN IS '첨부파일 유무';
COMMENT ON COLUMN BP_0411A.PPP_APPR_SEQ_NO IS '결의서번호';
COMMENT ON COLUMN BP_0411A.RESERVE_01_NM IS '추가 필드 1 명칭';
COMMENT ON COLUMN BP_0411A.RESERVE_01_CODE IS '추가 필드 1 코드';
COMMENT ON COLUMN BP_0411A.RESERVE_01_ERP_CD IS '추가 필드 1 ERP 코드';
COMMENT ON COLUMN BP_0411A.EVENT_DATETIME IS '실행일시';
COMMENT ON COLUMN BP_0411A.START_DTM IS '시작일시';
COMMENT ON COLUMN BP_0411A.END_DTM IS '종료일시';
COMMENT ON COLUMN BP_0411A.EVENT_DTM IS '일시/기간';
COMMENT ON COLUMN BP_0411A.ASSET_DIV_NM IS '예산부문명';
COMMENT ON COLUMN BP_0411A.ASSET_DEPT_NM IS '예산부서명';
COMMENT ON COLUMN BP_0411A.ASSET_DIV_ERP_CD IS '예산부문ERP코드';
COMMENT ON COLUMN BP_0411A.ASSET_DEPT_ERP_CD IS '예산부서ERP코드';
COMMENT ON COLUMN BP_0411A.DEDCT_YN IS '공제여부';
COMMENT ON COLUMN BP_0411A.BIZ_UNIT_NM2 IS '사업/프로젝트명2';
COMMENT ON COLUMN BP_0411A.BIZ_UNIT_ERP_CD2 IS '구분 ERP 코드2';
COMMENT ON COLUMN BP_0411A.PAY_ACCOUNT_NO IS '지급계좌번호';
COMMENT ON COLUMN BP_0411A.PAY_HOLDER_NAME IS '지급예금주명';
COMMENT ON COLUMN BP_0411A.PAY_BANK IS '지급은행';
COMMENT ON COLUMN BP_0411A.EXPN_PAY_DT IS '경비지급 완료일자';
COMMENT ON COLUMN BP_0411A.EXPN_PRE_DT IS '경비지급 예정일자';
COMMENT ON COLUMN BP_0411A.DOC_NO IS '문서번호';
COMMENT ON COLUMN BP_0411A.SUMMARY_7 IS '내용7';
COMMENT ON COLUMN BP_0411A.SUMMARY_8 IS '내용8';
COMMENT ON COLUMN BP_0411A.RSCH_CD IS '연구과제 코드';
COMMENT ON COLUMN BP_0411A.RSCH_NM IS '연구과제 항목';
COMMENT ON COLUMN BP_0411A.ADVC_CD IS '전도금 코드';
COMMENT ON COLUMN BP_0411A.ADVC_NM IS '전도금 항목';
COMMENT ON COLUMN BP_0411A.CARD_ERP_CD IS '법인카드ERP코드';
COMMENT ON COLUMN BP_0411A.CARD_NICK_NM IS '카드별칭';
COMMENT ON COLUMN BP_0411A.DRAFT_DATE IS '결재요청일자';
COMMENT ON COLUMN BP_0411A.PTL_ID IS '비즈플레이 내부 관리 키';
COMMENT ON COLUMN BP_0411A.USE_INTT_ID IS '이용기관ID';
COMMENT ON COLUMN BP_0411A.LST_APRV_DATE IS '결재완료일자';
COMMENT ON COLUMN BP_0411A.APPR_SEQ_NO IS '지출결의서번호';
COMMENT ON COLUMN BP_0411A.RESOLLIST_SEQ_NO IS '결의서증빙순번';
COMMENT ON COLUMN BP_0411A.PROC_BANK_ACCT_NO IS '지급계좌번호(입력항목)';
COMMENT ON COLUMN BP_0411A.PROC_HOLDER_NAME IS '지급계좌소유주명(입력항목)';
COMMENT ON COLUMN BP_0411A.PROC_BANK_NM IS '지급계좌명(입력항목)';
COMMENT ON COLUMN BP_0411A.CAN_MG IS '미처리메시지';
COMMENT ON COLUMN BP_0411A.ERP_STAT_NO IS 'ERP전표번호';
COMMENT ON COLUMN BP_0411A.CAR_INFO IS '차량번호';

-- 비즈플레이 PK 추가
ALTER TABLE BP_0411A
  ADD CONSTRAINT "BP_0411A_PK" PRIMARY KEY ("CARD_NO", "SEQ", "APV_DT");

-- 비즈플레이 첨부파일 생성
CREATE TABLE BP_0411A_FILE (
    CARD_NO VARCHAR2(19),
    SEQ VARCHAR2(10),
    APV_DT VARCHAR2(8),
    IMG_SEQ_NO VARCHAR2(3),
    REG_DTM VARCHAR2(20),
    RCPT_IMG_URL VARCHAR2(200),
    ORG_IMG_URL VARCHAR2(200),
    IMG_NM VARCHAR2(200)
);

-- 비즈플레이 첨부파일 FK 추가
ALTER TABLE BP_0411A_FILE
  ADD CONSTRAINT "BP_0411A_FILE_FK" FOREIGN KEY ("CARD_NO", "SEQ", "APV_DT") REFERENCES BP_0411A ("CARD_NO", "SEQ", "APV_DT");

-- 비즈플레이 첨부파일 코멘트
COMMENT ON COLUMN BP_0411A_FILE.CARD_NO IS '카드번호';
COMMENT ON COLUMN BP_0411A_FILE.SEQ IS '일련번호';
COMMENT ON COLUMN BP_0411A_FILE.APV_DT IS '승인일자';
COMMENT ON COLUMN BP_0411A_FILE.IMG_SEQ_NO IS '증빙일련번호';
COMMENT ON COLUMN BP_0411A_FILE.REG_DTM IS '등록일시';
COMMENT ON COLUMN BP_0411A_FILE.RCPT_IMG_URL IS '증빙이미지';
COMMENT ON COLUMN BP_0411A_FILE.ORG_IMG_URL IS '증빙이미지_원본';
COMMENT ON COLUMN BP_0411A_FILE.IMG_NM IS '증빙이미지_이름';

-- 비즈플레이 결재라인 생성
CREATE TABLE BP_0411A_LINE (
    PPP_APPR_SEQ_NO VARCHAR2(20),
    APRV_EMP_CD VARCHAR2(20),
    APPR_KIND VARCHAR2(1),
    APPV_SEQ_NO VARCHAR2(3),
    APRV_LINE_NM VARCHAR2(20),
    APRV_DATE VARCHAR2(20),
    APRV_USER_GB VARCHAR2(2),
    APRV_USER_DEPT_NM VARCHAR2(50)
);

-- 비즈플레이 결재라인 PK 추가
ALTER TABLE BP_0411A_LINE
  ADD CONSTRAINT "BP_0411A_LINE_PK" PRIMARY KEY ("PPP_APPR_SEQ_NO", "APRV_EMP_CD", "APPR_KIND");
  
-- 비즈플레이 결재라인 코멘트 추가
COMMENT ON COLUMN BP_0411A_LINE.PPP_APPR_SEQ_NO IS '결의서번호';
COMMENT ON COLUMN BP_0411A_LINE.APRV_EMP_CD IS '결재자코드';
COMMENT ON COLUMN BP_0411A_LINE.APPR_KIND IS '결재종류';
COMMENT ON COLUMN BP_0411A_LINE.APRV_LINE_NM IS '결재자명';
COMMENT ON COLUMN BP_0411A_LINE.APPV_SEQ_NO IS '결재순번';
COMMENT ON COLUMN BP_0411A_LINE.APRV_DATE IS '결재일자';
COMMENT ON COLUMN BP_0411A_LINE.APRV_USER_GB IS '결재자구분';
COMMENT ON COLUMN BP_0411A_LINE.APRV_USER_DEPT_NM IS '결재자부서명';
  
-- 캘린더 결재 여부 컬럼 추가
ALTER TABLE STD_CAL_MNG ADD(APRV_YN VARCHAR2(1) DEFAULT 'N');
COMMENT ON COLUMN STD_CAL_MNG.APRV_YN IS '결재 여부';

-- 결재 기간 컬럼 추가
ALTER TABLE STD_APRV_MNG ADD(TERM_ST_HM VARCHAR2(4));
ALTER TABLE STD_APRV_MNG ADD(TERM_ED_HM VARCHAR2(4));
COMMENT ON COLUMN STD_APRV_MNG.TERM_ST_HM IS '기간 시작 시간';
COMMENT ON COLUMN STD_APRV_MNG.TERM_ED_HM IS '기간 종료 시간';

-- 비즈플레이 공통코드
CREATE TABLE BP_CD (
    BP_CD VARCHAR2(20),
    BP_CD_NM VARCHAR2(50)
);

-- 비즈플레이 공통코드 PK
ALTER TABLE BP_CD
  ADD CONSTRAINT "BP_CD_PK" PRIMARY KEY ("BP_CD");
  
-- 비즈플레이 공통코드 코멘트
COMMENT ON COLUMN BP_CD.BP_CD IS '비즈플레이 코드';
COMMENT ON COLUMN BP_CD.BP_CD_NM IS '비즈플레이 코드 이름';

-- 비즈플레이 공통코드 데이터 추가
INSERT INTO BP_CD VALUES('30000001', 'KB');
INSERT INTO BP_CD VALUES('30000002', '현대');
INSERT INTO BP_CD VALUES('30000003', '삼성');
INSERT INTO BP_CD VALUES('30000004', '외환');
INSERT INTO BP_CD VALUES('30000006', '비씨');
INSERT INTO BP_CD VALUES('30000008', '신한');                                 
INSERT INTO BP_CD VALUES('30000010', '하나');                                  
INSERT INTO BP_CD VALUES('30000012', '광주');
INSERT INTO BP_CD VALUES('30000013', '수협');                                 
INSERT INTO BP_CD VALUES('30000014', '전북');
INSERT INTO BP_CD VALUES('30000015', '하나');
INSERT INTO BP_CD VALUES('30000016', '씨티');
INSERT INTO BP_CD VALUES('30000017', '아멕스(롯데)');
INSERT INTO BP_CD VALUES('30000018', '우리');
INSERT INTO BP_CD VALUES('30000019', '롯데(개인카드)');
INSERT INTO BP_CD VALUES('30000020', '산은');
INSERT INTO BP_CD VALUES('30000021', 'NH');
INSERT INTO BP_CD VALUES('30000060', '비씨(기업)');
INSERT INTO BP_CD VALUES('30000061', '비씨(SC)');
INSERT INTO BP_CD VALUES('30000062', '비씨(부산)');
INSERT INTO BP_CD VALUES('30000063', '비씨(대구)');
INSERT INTO BP_CD VALUES('30000064', '비씨(경남)');
INSERT INTO BP_CD VALUES('30000065', '비씨(우리)');
INSERT INTO BP_CD VALUES('30000066', '비씨(하나)');
INSERT INTO BP_CD VALUES('30000067', '비씨(농협)');
INSERT INTO BP_CD VALUES('30000068', '비씨(국민)');
INSERT INTO BP_CD VALUES('30000069', '비씨(신한)');
INSERT INTO BP_CD VALUES('30000070', '비씨(씨티)');
INSERT INTO BP_CD VALUES('80000001', '기타(간이)영수증');

-- 사원 계좌정보 컬럼 추가
ALTER TABLE STD_USS_MNG ADD(BANK_NM VARCHAR2(40), BANK_NO VARCHAR2(20));
COMMENT ON COLUMN STD_USS_MNG.BANK_NM IS '은행명';
COMMENT ON COLUMN STD_USS_MNG.BANK_NO IS '계좌번호';